kind = "DojoContract"
class_hash = "0x6f05ce67121b11889a174816cda605a117fc7dce360edd8a5f39cbe11422a9b"
original_class_hash = "0x6f05ce67121b11889a174816cda605a117fc7dce360edd8a5f39cbe11422a9b"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/midgard_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "midgard::systems::actions::actions"
