kind = "DojoContract"
class_hash = "0x21b5f201203c74cf00484ae4fe09fc01ed8f57fe1de8e428d8e629aa609ae1"
original_class_hash = "0x21b5f201203c74cf00484ae4fe09fc01ed8f57fe1de8e428d8e629aa609ae1"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/midgard_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "midgard::systems::actions::actions"
